### ISSUE TITLE
Requeired Package

### ISSUE THREAD

**Issue by jooozo** [AndreLuisCelestino/OpenToolsAPI-EC2020#1]
Fui tentar compilar o exemplo e deu erro  [dcc32 Fatal Error] E2202 Required package 'bindcompvclsmp' not found 

Meu delphi é Embarcadero® Delphi 10.3 Version 26.0.36039.7899

**Comment by AndreLuisCelestino** [comment]
@jooozo , esse exemplo foi implementado no Delphi 10.4 (Sydney). Esse pode ser o problema de incompatibilidade.
De qualquer forma, como a maioria dos desenvolvedores estão no 10.3 (Rio), vou recompilar o exemplo e avisá-lo aqui.

**Comment by AndreLuisCelestino** [comment]
@jooozo , pode testar novamente?

**Comment by jooozo** [comment]
> @jooozo , pode testar novamente?

Deu certo! Obrigado!
